version: "3.5"
services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es
    environment:
      - node.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "E:/docker_volume/es-eshop:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kib:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - elastic
    depends_on:
        - es

  app:
    image: "e-tech-store-scrapy:1.0"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
#    command: "python ./eTechStore/main.py"
#    volumes:
#    - "E:/docker_volume/app-eshop:/eTechStore"
    networks:
      - elastic
    depends_on:
        - es

networks:
  elastic:
    driver: bridge